steps:
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --cache=true
  - --cache-ttl=168h
  - --destination=us-central1-docker.pkg.dev/glowing-funicular/registry/app:latest
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - run
  - deploy
  - app
  - --allow-unauthenticated
  - --execution-environment=gen2
  - --image=us-central1-docker.pkg.dev/glowing-funicular/registry/app:latest
  - --region=us-central1
